name: apm-copter
source: http://github.com/erlerobot/
vendor: Victor Mayoral Vilches <victor@erlerobot.com>
version: 1.9
architecture: [amd64, armhf]
frameworks: [capes]
services:
    - name: apm
      start: apm.sh
      poststop: apm.sh
      description: APM:Copter autopilot
      security-policy:
          apparmor: meta/apm.profile
          seccomp: meta/apm.seccomp
